#!/bin/sh

echo "qdbd files: "
find qdb/db

echo "qdbd.secure files: "
find qdb/securedb

pkill -SIGKILL -f qdbd

echo "qdb/log/qdbd.log: "
cat qdb/log/qdbd.log

echo "qdb/securelog/qdbd.log: "
# cat qdb/securelog/qdbd.log
